couchdb:
  build: couchdb
  volumes_from:
    - couchdbdata
  volumes:
    - /usr/local/var/lib/couchdb:/usr/local/var/lib/couchdb:rw
  ports:
    - "5984:5984"
    - "6984:6984"
couchdbdata:
  build: data
